# Generated by Django 3.1.4 on 2020-12-07 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='other')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('num_person', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('family', 'family')], max_length=50)),
                ('num_room', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='room_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('checkedIn', 'checkedIn')], max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.PositiveSmallIntegerField(default=0)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2020, 12, 7, 16, 33, 2, 541970))),
                ('reservation_status', models.CharField(choices=[('confirmed', 'confirmed'), ('checkedIn', 'checkedIn'), ('checkedOut', 'checkedOut'), ('pending', 'pending')], default='pending', max_length=50)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomdetail')),
            ],
        ),
    ]
